### PR TITLE
Package zectl for debian

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Comment by johnramsden** [comment]
Thanks @sonicaj ! That's great, I'll test and review it this weekend and integrate it into the release process.

**Comment by sonicaj** [comment]
Thank you @johnramsden, please let me know if you require anything from my end. Happy to be of help ; )

**Comment by johnramsden** [comment]
A few questions, comments:

* The `PLUGINS_DIRECTORY` variable should be set - [docs/BUILDING.md#building](https://github.com/johnramsden/zectl/blob/master/docs/BUILDING.md#building)
* Does this use `cmake` under the hood? I don't see it being invoked.

**Comment by johnramsden** [comment]
Could you also move the `debian` directory under `packaging`?

**Comment by sonicaj** [comment]
I can certainly do that but debian packaging expects debian directory at the top. Please let me know if you still would like me to do that. Thanks

**Comment by johnramsden** [comment]
I answered my own question about `cmake`, it does appear to be running it, I guess it has some sort of Debian helper that detects it should use `cmake`?

I think for now we will move it under the sub-directory, just to keep things neat. It can always be copied before the build process.

Other than adding the `PLUGINS_DIRECTORY`, and moving the `debian` directory everything looks good, worked great when I tested.

Steps I went through in testing on Debian 10:

```
apt install build-essential cmake libzfslinux-dev pkgconf
dpkg-buildpackage -b -rfakeroot -us -uc
apt install../zectl_0.1.1-1_amd64.deb
zectl list
```

**Comment by sonicaj** [comment]
Can you please elaborate `PLUGINS_DIRECTORY` comment ? I am not sure I completely follow ?

About debhelper, yes it does that automatically, though if we have some cmake magic going on or want to tweak some configuration bits, that can be done as well at different debian port stages.

About the `debian` directory, I'll move it to `packaging` for now but JFYI that's not standard as most debian based build systems don't recognise this repo having a valid debian package then ( if someone is using the repo directly ) to the best of my knowledge.

Btw glad to see it worked for you as well. I'll quickly make the required amends ; )

**Comment by sonicaj** [comment]
@johnramsden I have moved the `debian` directory, please let me know if there's anything else required. Thanks

**Comment by johnramsden** [comment]
The location for plugins needs to be defined at compile time by setting `PLUGINS_DIRECTORY`:

Usually that would be done in this form using cmake:

```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DPLUGINS_DIRECTORY=/usr/share/zectl/libze_plugin
```

Otherwise the plug-in gets installed to the source directory, this is only really useful for development. If it is not set plugins won't work.

For example, if I don't set it, and I install to a release subdirectory this is where the plug-in ends up:

```
release/home/john/Workspace/C/zectl/build/lib/libze_plugin/libze_plugin_systemdboot.so
```

**Comment by sonicaj** [comment]
Thank you for clarifying @johnramsden, I unfortunately missed it. I have added the requested changes. Please let me know if anything else is required. Thanks

**Pull request merged**
