### PR TITLE
Proposed solution for automatic manpage recreation.

### LINKED ISSUE #49: Manpage not being automatically rebuilt
While doing some other work I noticed that the manpage file was not being recreated automatically.  There seems to be no infrastructure in place to do this.

### PR DESCRIPTION
**Pull request by GregoryLand**
I created a way of handling rebuilding of manpages to resolve #49.  Feel free to comment or request changes.

### CODE REVIEW

**Comment by johnramsden** [comment]
Thanks @GregoryLand

Im getting the following:

```
[ 91%] Generating man page : zectl.8.scd -> zectl.8
/bin/sh: line 1: SCDOC-NOTFOUND: command not found
make[2]: *** [docs/CMakeFiles/manpages.dir/build.make:71: docs/zectl.8] Error 127
make[2]: *** Deleting file 'docs/zectl.8'
make[1]: *** [CMakeFiles/Makefile2:263: docs/CMakeFiles/manpages.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

scdoc is installed:

```
$ which scdoc
/usr/sbin/scdoc
```

**Comment by GregoryLand** [comment]
Are you using the scdoc Arch package?  If so it should be in /usr/bin/scdoc.  Can you give me some details on your build environment?  I don't think /usr/sbin is part of my local systems $PATH.  Could you check your $PATH variable for me?

**Comment by johnramsden** [comment]
Oh, i made a new shell, works now. Thanks! Merged.

```
lrwxrwxrwx 1 root root 3 Sep 18 06:18 /usr/sbin -> bin
```

**Comment by GregoryLand** [comment]
Okay good.  With the Arch package the scdoc.pc file has 
`prefix=/usr
exec_prefix=${prefix}
scdoc=${exec_prefix}/bin/scdoc
` in it.  I was pretty sure using find_program was the right call there.  Glad it works now.

**Pull request merged**
